### Name : Muhammad Abubakar Siddique
### Class : BSAI - 3C
### Roll No. 138
### Subject : AI (LAB) 
### Project topic : Stores Sales Forecasting

<div class="alert alert-block alert-info">
    Import <b>Libraries</b>
</div>

In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import LabelEncoder

<div class="alert alert-block alert-info">
    1. <b>Data Gathering</b> : <a href="https://www.kaggle.com/datasets/tanayatipre/store-sales-forecasting-dataset?utm_source=chatgpt.com">Click Me</a>
    <br>
    2. <b>Data Loading</b>
</div>

In [2]:
df = pd.read_csv("processed_data.csv", encoding='cp1252')
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,0,0,137,15,42420,2,FUR-BO-10001798,0,Bookcases,261,2,0,41
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,0,0,137,15,42420,2,FUR-CH-10000454,0,Chairs,731,3,0,219
2,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,0,0,108,8,33311,2,FUR-TA-10000577,0,Tables,957,5,0,-383
3,6,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,0,0,184,3,90032,3,FUR-FU-10001487,0,Furnishings,48,7,0,14
4,11,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,0,0,184,3,90032,3,FUR-TA-10001539,0,Tables,1706,9,0,85
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2116,9963,CA-2015-168088,3/19/2015,3/22/2015,First Class,CM-12655,Corinna Mitchell,2,0,146,40,77041,0,FUR-BO-10004218,0,Bookcases,383,4,0,-67
2117,9965,CA-2016-146374,12/5/2016,12/10/2016,Second Class,HE-14800,Harold Engle,1,0,233,6,19711,1,FUR-FU-10002671,0,Furnishings,13,1,0,6
2118,9981,US-2015-151435,9/6/2015,9/9/2015,Second Class,SW-20455,Shaun Weien,0,0,160,16,70506,2,FUR-TA-10001039,0,Tables,85,1,0,22
2119,9990,CA-2014-110422,1/21/2014,1/23/2014,Second Class,TB-21400,Tom Boeckenhauer,0,0,206,8,33180,2,FUR-FU-10001889,0,Furnishings,25,3,0,4
2120,9991,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,0,0,72,3,92627,3,FUR-FU-10000747,0,Furnishings,91,2,0,15

<div class="alert alert-block alert-info">
    3. <b>Data Exploration</b>
</div>

In [4]:
df.head(3)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,0,0,137,15,42420,2,FUR-BO-10001798,0,Bookcases,261,2,0,41
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,0,0,137,15,42420,2,FUR-CH-10000454,0,Chairs,731,3,0,219
2,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,0,0,108,8,33311,2,FUR-TA-10000577,0,Tables,957,5,0,-383

In [5]:
df.tail(3)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Sales,Quantity,Discount,Profit
2118,9981,US-2015-151435,9/6/2015,9/9/2015,Second Class,SW-20455,Shaun Weien,0,0,160,16,70506,2,FUR-TA-10001039,0,Tables,85,1,0,22
2119,9990,CA-2014-110422,1/21/2014,1/23/2014,Second Class,TB-21400,Tom Boeckenhauer,0,0,206,8,33180,2,FUR-FU-10001889,0,Furnishings,25,3,0,4
2120,9991,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,0,0,72,3,92627,3,FUR-FU-10000747,0,Furnishings,91,2,0,15

In [6]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

In [7]:
df.count()

Row ID           2121
Order ID         2121
Order Date       2121
Ship Date        2121
Ship Mode        2121
Customer ID      2121
Customer Name    2121
Segment          2121
Country          2121
City             2121
State            2121
Postal Code      2121
Region           2121
Product ID       2121
Category         2121
Sub-Category     2121
Sales            2121
Quantity         2121
Discount         2121
Profit           2121
dtype: int64

In [8]:
df.describe()

,Row ID,Segment,Country,City,State,Postal Code,Region,Category,Sales,Quantity,Discount,Profit
count,2121.000000,2121.000000,2121.0,2121.000000,2121.000000,2121.000000,2121.000000,2121.0,2121.000000,2121.000000,2121.0,2121.000000
mean,5041.643564,0.645922,0.0,193.859029,21.798208,55726.556341,1.596417,0.0,349.266855,3.785007,0.0,8.545969
std,2885.740258,0.755198,0.0,97.545420,15.348616,32261.888225,1.166864,0.0,503.176292,2.251620,0.0,135.819059
min,1.000000,0.000000,0.0,0.000000,0.000000,1040.000000,0.000000,0.0,1.000000,1.000000,0.0,-1862.000000
25%,2568.000000,0.000000,0.0,110.000000,4.000000,22801.000000,1.000000,0.0,47.000000,2.000000,0.0,-12.000000
50%,5145.000000,0.000000,0.0,200.000000,25.000000,60505.000000,1.000000,0.0,182.000000,3.000000,0.0,7.000000
75%,7534.000000,1.000000,0.0,270.000000,35.000000,90032.000000,3.000000,0.0,435.000000,5.000000,0.0,33.000000
max,9991.000000,2.000000,0.0,370.000000,47.000000,99301.000000,3.000000,0.0,4416.000000,14.000000,0.0,1013.000000

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2121 entries, 0 to 2120
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         2121 non-null   int64
 1   Order ID       2121 non-null   object
 2   Order Date     2121 non-null   object
 3   Ship Date      2121 non-null   object
 4   Ship Mode      2121 non-null   object
 5   Customer ID    2121 non-null   object
 6   Customer Name  2121 non-null   object
 7   Segment        2121 non-null   int64
 8   Country        2121 non-null   int64
 9   City           2121 non-null   int64
 10  State          2121 non-null   int64
 11  Postal Code    2121 non-null   int64
 12  Region         2121 non-null   int64
 13  Product ID     2121 non-null   object
 14  Category       2121 non-null   int64
 15  Sub-Category   2121 non-null   object
 16  Sales          2121 non-null   int64
 17  Quantity       2121 non-null   int64
 18  Discount       2121 non-null   int64
 19  Profit         2121 non-null   int64
dtypes: int64(12), object(8)
memory usage: 331.5+ KB

In [10]:
df.shape
print(f"Number of Rows: {df.shape[0]} and Number of Columns: {df.shape[1]}")

Number of Rows: 2121 and Number of Columns: 20

In [11]:
df['City'].unique()

array([137, 108, 184, 264, 249, 285, 146, 230, 341,  54, 200,  65, 211,
       232,  14, 316, 365,  24, 292, 233, 110, 304,  84, 199,  90,  87,
       329, 166, 307,  66,  64,  20,  10, 129, 224, 191, 260, 174, 150,
        43,   0,  67,  82, 265, 253,   4,  72, 254, 119, 165, 109, 151,
       286, 306,  80, 353, 348, 349,   9,  60, 346, 357, 180,  88, 242,
       340, 300,  85, 168, 163, 247,  95, 313, 106, 185, 183, 323, 288,
       239, 210, 339, 204, 294,  13, 246, 354, 152, 299, 289, 206, 369,
       217,  99, 153,  75, 133, 290,  70,  28, 113,  52, 159, 256, 101,
       342, 266, 276, 320, 207, 350, 120, 238,   3, 161, 102, 356,  97,
       261,  45, 155, 160, 241, 325, 189, 309, 282, 226,  48,  27, 322,
       103,  32, 218,  29, 275, 270, 248, 219, 281, 326, 169, 121, 370,
        63,  76,  57, 170, 303, 178, 195, 179,  18, 321, 293, 318, 295,
       147, 144, 104, 258, 105, 213, 360, 315, 190,  22,   1, 363, 278,
       343, 139, 118, 186, 140, 167,  16, 271,  71, 283, 171,  51, 367,
        12, 331, 162, 141, 296, 319,   2, 223, 225, 263, 359,  33, 177,
       127,  50, 203,  15, 328, 107, 128, 277,  30, 214, 172, 136, 337,
        91, 149, 284,  81, 215,  44, 298, 267, 188, 268,  62, 338, 205,
       243, 358,  56, 124,  46, 132, 126, 229, 368, 154, 273, 212, 112,
       111,  25,  74,  17, 272,  58,  37, 231, 308, 130, 311, 201, 175,
       131, 291, 193,  78, 355,  35, 257, 194, 255, 176, 115, 244,  39,
        83,   5,  47, 156, 330, 208, 352, 332,  23, 116, 157, 364, 240,
       252, 245,  89, 158, 222,   8, 301, 269,   7, 209,  36, 164,  68,
       202,  53, 280, 134,  40, 228, 117, 317, 187, 274, 138,  55, 100,
       251, 361, 250,  98, 333, 351,  49, 366, 287, 145, 259, 335,  96,
       227, 237, 182, 236, 302, 297, 344, 327, 135,  21,  86,  38,  41,
       336,  73, 362, 181, 125, 234,  26, 334, 221,  61,  42,  93, 216,
       279,  92,  79,   6,  11,  77, 235,  59, 114, 312, 310, 122, 192,
       142, 345, 347, 324,  69, 123, 196, 143, 173,  94, 262, 198, 220,
        31,  19, 197, 314,  34, 305, 148], dtype=int64)

In [12]:
df.nunique()

Row ID           2121
Order ID         1764
Order Date        889
Ship Date         960
Ship Mode           4
Customer ID       707
Customer Name     707
Segment             3
Country             1
City              371
State              48
Postal Code       454
Region              4
Product ID        375
Category            1
Sub-Category        4
Sales             728
Quantity           14
Discount            1
Profit            472
dtype: int64

In [13]:
df.isnull().sum()

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

<div class="alert alert-block alert-info">
    4. <b>Data Pre-Processing</b>
</div>

In [14]:
df = df.drop('Quantity', axis=1)

In [15]:
# Mean, Median, Mode

df['Profit'].mean()
df['Profit'].median()
df['Profit'].mode()[0]

6

In [ ]:
# df['city'].fillna(df['city'].mode()[0], inplace=True)
# df['city'] = df['city'].fillna(df['city'].mode()[0])

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2121 entries, 0 to 2120
Data columns (total 19 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         2121 non-null   int64
 1   Order ID       2121 non-null   object
 2   Order Date     2121 non-null   object
 3   Ship Date      2121 non-null   object
 4   Ship Mode      2121 non-null   object
 5   Customer ID    2121 non-null   object
 6   Customer Name  2121 non-null   object
 7   Segment        2121 non-null   int64
 8   Country        2121 non-null   int64
 9   City           2121 non-null   int64
 10  State          2121 non-null   int64
 11  Postal Code    2121 non-null   int64
 12  Region         2121 non-null   int64
 13  Product ID     2121 non-null   object
 14  Category       2121 non-null   int64
 15  Sub-Category   2121 non-null   object
 16  Sales          2121 non-null   int64
 17  Discount       2121 non-null   int64
 18  Profit         2121 non-null   int64
dtypes: int64(11), object(8)
memory usage: 315.0+ KB

In [17]:
def fillNaObjectMode(cols):
    for i in cols:
        if i in df.columns:  # Safety check
            df[i] = df[i].fillna(df[i].mode()[0])

# Use cleaned column names (with spaces or underscores)
object_cols = ['Order_ID', 'Order_Date', 'Ship_Mode', 'Customer_ID', 'Customer_Name', 
               'Segment', 'Country', 'City', 'State', 'Region', 'Product_ID', 
               'Category', 'Sub_Category']

fillNaObjectMode(object_cols)

In [18]:
def fillNaIntMode(cols):   # ← Wrong name! Mode is bad for numbers
    for i in cols:
        if i in df.columns:
            df[i] = df[i].fillna(df[i].median())   # Use median for numbers!

# Correct columns with underscores
int_columns = ['Row_ID', 'Postal_Code', 'Quantity']

fillNaIntMode(int_columns)

In [19]:
# For Float Type
def fillnaFloatMean(cols):
    for i in cols:
        df[i] = df[i].fillna(df[i].mean())

columns = ['Sales','Discount','Profit']
fillnaFloatMean(columns)

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2121 entries, 0 to 2120
Data columns (total 19 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         2121 non-null   int64
 1   Order ID       2121 non-null   object
 2   Order Date     2121 non-null   object
 3   Ship Date      2121 non-null   object
 4   Ship Mode      2121 non-null   object
 5   Customer ID    2121 non-null   object
 6   Customer Name  2121 non-null   object
 7   Segment        2121 non-null   int64
 8   Country        2121 non-null   int64
 9   City           2121 non-null   int64
 10  State          2121 non-null   int64
 11  Postal Code    2121 non-null   int64
 12  Region         2121 non-null   int64
 13  Product ID     2121 non-null   object
 14  Category       2121 non-null   int64
 15  Sub-Category   2121 non-null   object
 16  Sales          2121 non-null   int64
 17  Discount       2121 non-null   int64
 18  Profit         2121 non-null   int64
dtypes: int64(11), object(8)
memory usage: 315.0+ KB

<div class="alert alert-block alert-warning">
    <b>Manage Data Types</b>
</div>

In [21]:
# For Float Type
def changeFloatToInt(cols):
    for i in cols:
        df[i] = df[i].astype('int64')

columns = ['Sales','Discount','Profit']
changeFloatToInt(columns)

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2121 entries, 0 to 2120
Data columns (total 19 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         2121 non-null   int64
 1   Order ID       2121 non-null   object
 2   Order Date     2121 non-null   object
 3   Ship Date      2121 non-null   object
 4   Ship Mode      2121 non-null   object
 5   Customer ID    2121 non-null   object
 6   Customer Name  2121 non-null   object
 7   Segment        2121 non-null   int64
 8   Country        2121 non-null   int64
 9   City           2121 non-null   int64
 10  State          2121 non-null   int64
 11  Postal Code    2121 non-null   int64
 12  Region         2121 non-null   int64
 13  Product ID     2121 non-null   object
 14  Category       2121 non-null   int64
 15  Sub-Category   2121 non-null   object
 16  Sales          2121 non-null   int64
 17  Discount       2121 non-null   int64
 18  Profit         2121 non-null   int64
dtypes: int64(11), object(8)
memory usage: 315.0+ KB

In [29]:
from sklearn.preprocessing import LabelEncoder

def convert_everything_to_int64(df):
    # Step 1: Convert object/categorical columns to integer via LabelEncoder
    for col in df.columns:
        if df[col].dtype == 'object':
            df[col] = LabelEncoder().fit_transform(df[col].astype(str))

    # Step 2: Convert all columns to int64
    df = df.astype('int64')
    
    return df

df = convert_everything_to_int64(df)

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2121 entries, 0 to 2120
Data columns (total 19 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         2121 non-null   int64
 1   Order ID       2121 non-null   int64
 2   Order Date     2121 non-null   int64
 3   Ship Date      2121 non-null   int64
 4   Ship Mode      2121 non-null   int64
 5   Customer ID    2121 non-null   int64
 6   Customer Name  2121 non-null   int64
 7   Segment        2121 non-null   int64
 8   Country        2121 non-null   int64
 9   City           2121 non-null   int64
 10  State          2121 non-null   int64
 11  Postal Code    2121 non-null   int64
 12  Region         2121 non-null   int64
 13  Product ID     2121 non-null   int64
 14  Category       2121 non-null   int64
 15  Sub-Category   2121 non-null   int64
 16  Sales          2121 non-null   int64
 17  Discount       2121 non-null   int64
 18  Profit         2121 non-null   int64
dtypes: int64(19)
memory usage: 315.0 KB

In [32]:
df.head(2)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Sales,Discount,Profit
0,1,881,229,149,2,127,147,0,0,137,15,42420,2,12,0,0,261,0,41
1,2,881,229,149,2,127,147,0,0,137,15,42420,2,55,0,1,731,0,219

In [33]:
df.to_csv('processed_data.csv', index=False, header=True)

In [34]:
df = pd.read_csv('processed_data.csv')
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Sales,Discount,Profit
0,1,881,229,149,2,127,147,0,0,137,15,42420,2,12,0,0,261,0,41
1,2,881,229,149,2,127,147,0,0,137,15,42420,2,55,0,1,731,0,219
2,4,1525,62,85,3,628,612,0,0,108,8,33311,2,319,0,3,957,0,-383
3,6,72,652,638,3,79,101,0,0,184,3,90032,3,185,0,2,48,0,14
4,11,72,652,638,3,79,101,0,0,184,3,90032,3,328,0,3,1706,0,85
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2116,9963,586,387,427,0,144,155,2,0,146,40,77041,0,40,0,0,383,0,-67
2117,9965,852,316,256,2,284,283,1,0,233,6,19711,1,232,0,2,13,0,6
2118,9981,1565,877,958,2,648,619,0,0,160,16,70506,2,323,0,3,85,0,22
2119,9990,48,26,29,2,658,676,0,0,206,8,33180,2,200,0,2,25,0,4
2120,9991,1133,346,450,3,169,181,0,0,72,3,92627,3,164,0,2,91,0,15

<div class="alert alert-block alert-info">
    5. <b>Train - Test Splitting</b>
</div>

In [35]:
import pandas as pd
df = pd.read_csv('processed_data.csv')
# df.info()
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Sales', 'Discount', 'Profit'],
      dtype='object')

In [36]:
X = df.drop('Profit', axis=1)   # Dependant columns / Input columns
y = df['Profit']                # Resultant columns / Output column

In [37]:
from sklearn.model_selection import train_test_split
train_X, test_X, train_y, test_y = train_test_split(X,y, test_size=0.3, shuffle=False) # 80:20, 70:30, 60:40

In [38]:
print(train_X.shape, train_y.shape)
print(test_X.shape, test_y.shape)

(1484, 18) (1484,)
(637, 18) (637,)

<div class="alert alert-block alert-info">
    6. <b>Regression / Model Training</b>
</div>

In [41]:
from sklearn.svm import SVR           # ← SVR = Support Vector Regressor
from sklearn.metrics import mean_squared_error, r2_score

In [42]:
model_svr = SVR(kernel='rbf')         # ya 'linear', 'poly' etc.
model_svr.fit(train_X, train_y)

# Prediction
pred_y = model_svr.predict(test_X)

In [ ]:
print("MSE:", mean_squared_error(test_y, pred_y))
print("RMSE:", mean_squared_error(test_y, pred_y, squared=False))
print("R² Score:", r2_score(test_y, pred_y))

MSE: 21168.463959556502
RMSE: 145.4938622745183
R² Score: 0.0051952718140954035

d:\Anaconda\Lib\site-packages\sklearn\metrics\_regression.py:483: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(

In [48]:
from sklearn.metrics import r2_score, mean_squared_error

pred_y = model_svr.predict(test_X)

# Accuracy-like metric
r2 = r2_score(test_y, pred_y)
print("R² Score (Regression Accuracy):", round(r2*100, 2), "%")

R² Score (Regression Accuracy): 0.52 %

In [52]:
import pickle
pickle.dump(model_svr, open('model_svr.pkl', 'wb'))   # Model Saving

In [53]:
import pickle
model_svc = pickle.load(open('model_svr.pkl', 'rb'))  # Model Loading